config/routes.rb
Rails.application.routes.draw do
  devise_for :airlines
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/my_planes", to: "planes#my_planes"
  resources :planes do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:destroy, :index, :edit, :update] do
    member do
      patch :accepted
      patch :refused
    end
  end
end

app/models/airline.rb
class Airline < ApplicationRecord
  has_many :planes
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :plane
  belongs_to :airline
  
end

app/models/plane.rb
class Plane < ApplicationRecord
  belongs_to :airline
  has_many :bookings
  has_one_attached :photo
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_airline!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def pundit_user
    current_airline
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    skip_policy_scope

    @bookings_as_renter = current_airline.bookings.order(start_date: :asc)
    # all the bookings that the current airline made

    @planes = current_airline.planes
    # all the plane of the current airline online

    @bookings_as_owner = Booking.where(plane: @planes)

    @current_bookings = @bookings_as_owner.where(status: "accepted").where("DATE(end_date) >= ?", Date.today).order(end_date: :asc)

    @current_bookings_present = @current_bookings.where("DATE(start_date) <= ?", Date.today).order(start_date: :desc)

    @current_bookings_futur = @current_bookings.where("DATE(start_date) > ?", Date.today).order(start_date: :desc)

    @old_bookings = @bookings_as_owner.where.not(status: "pending").where("DATE(end_date) < ?", Date.today).order(end_date: :desc)

    # all the bookings request for the current airline planes
  end

  def new
    @plane = Plane.find(params[:plane_id])
    @booking = Booking.new
    @booking.plane = @plane
    authorize @booking
  end

  def create
    @plane = Plane.find(params[:plane_id])
    @booking = Booking.new(booking_params)
    authorize @booking
    @booking.plane = @plane
    @booking.airline = current_airline

    if @booking.save
      redirect_to bookings_path, notice: "Booking request done"
    else
      render :new
    end
  end

  def edit
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.update(booking_params)
    redirect_to bookings_path
  end

  def accepted
    @booking = Booking.find(params[:id])
    authorize @booking

    @booking.update(status: "accepted")
    redirect_to bookings_path(tabactive: true)
  end

  def refused
    @booking = Booking.find(params[:id])
    authorize @booking

    @booking.update(status: "refused")
     redirect_to bookings_path(tabactive: true)
  end

  private

  def booking_params
    params.require(:booking).permit(:status, :start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_airline!, only: :home

  def home
    @planes = Plane.all
  end
end

app/controllers/planes_controller.rb
class PlanesController < ApplicationController
  def index
    @planes = Plane.all
    # @planes = policy_scope(Plane)
    skip_policy_scope
    if params[:query].present?
      sql_query = " \
        planes.name ILIKE :query \
        OR planes.location ILIKE :query \
        OR airlines.name ILIKE :query \
      "
      @planes = Plane.joins(:airline).where(sql_query, query: "%#{params[:query]}%")
    else
      @planes = Plane.all
    end

    #@planes = policy_scope(Plane)

    @markers = @planes.geocoded.map do |plane|
      {
        lat: plane.latitude,
        lng: plane.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { plane: plane }),
        image_url: helpers.asset_url('airplane.png'),
        plane_id: plane.id
      }
    end

  end

  def show
    @booking = Booking.new
    @plane = Plane.find(params[:id])
    @booking.plane = @plane
    authorize @plane
  end

  def new
    @plane = Plane.new
    authorize @plane
  end

  def create
    @plane = Plane.new(plane_params)
    @plane.airline = current_airline
    authorize @plane
    if @plane.save
      redirect_to my_planes_path(@plane)
    else
      render :new
    end
  end

  def edit
    @plane = Plane.find(params[:id])
    authorize @plane
  end

  def update
    @plane = Plane.find(params[:id])
    @plane.update(plane_params)
    authorize @plane
    if @plane.save
      redirect_to plane_path(@plane)
    else
      render :edit
    end
  end

  def destroy
    @plane = Plane.find(params[:id])
    @plane.destroy
    authorize @plane
    redirect_to my_planes_path
  end

  def my_planes
    skip_authorization
    
    @planes = current_airline.planes.order(id: :desc)

    # @planes = policy_scope(Plane)
  end

  private

  def plane_params
    params.require(:plane).permit(:name, :location, :capacity, :price_per_day, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class="container text-center pt-5 w-500">
  <div class="form-style">
    <br>
    <%= simple_form_for @booking do |f| %>
    <%= f.input :status, collection: ["accepted", "refused", "pending"] %>
    <%= f.submit "Update" %>
     <% end %>
  </div>
</div>

app/views/bookings/index.html.erb
<nav>
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
    <a class="nav-item nav-link <%='active' if !params[:tabactive]%>" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true"> My bookings </a>
    <a class="nav-item nav-link <%='active' if params[:tabactive]%>" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false"> New requests received (<%= @bookings_as_owner.reject{|b| b.status != "pending"}.count %>) </a>
    <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false"> Accepted requests (<%= @current_bookings.count %>)</a>
    <a class="nav-item nav-link" id="nav-history-tab" data-toggle="tab" href="#nav-history" role="tab" aria-controls="nav-history" aria-selected="false"> History</a>
  </div>
</nav>


<div class="tab-content" id="nav-tabContent">
  <div class="tab-pane fade <%='show active' if !params[:tabactive]%>" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
    <div class="container">
      <% @bookings_as_renter.each do |booking| %>
        <div class="card-product mt-3 ">
          <% if booking.plane.photo.attached? %>
            <%= cl_image_tag plane.photo.key %>
          <% else %>
            <img src="https://aircharterservice-globalcontent-live.cphostaccess.com/images/home_tcm36-2071.jpg" />
          <% end %>
          <div class="card-product-infos">
            <ul class="list-unstyled">
              <li><i class="fas fa-rocket"></i> <%= link_to booking.plane.name.to_s, plane_path(booking.plane), class: 'card-link' %> <em>owned by</em> <strong> <%= booking.plane.airline.name%> </strong></li>
              <li><i class="fas fa-plane-departure"></i> <strong>Airport:</strong> <%= booking.plane.location %> </li>
              <li><i class="far fa-calendar-alt"></i> <strong>from:</strong> <%= booking.start_date.strftime("%d/%m/%Y")%> <strong>to:</strong> <%=booking.end_date.strftime("%d/%m/%Y")%></li>
              <li><i class="far fa-compass"></i> <strong>Status:</strong> <%= booking.status %> </li>
            </ul>
          </div>
        </div>
      <% end %>
  </div>
</div>



<div class="tab-pane <%='show active' if params[:tabactive]%>" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
  <div class="container mt-4">
    <% @bookings_as_owner.reject{|b| b.status != "pending"}.each do |booking| %>
      <div class="card-product mb-2">
        <% if booking.plane.photo.attached? %>
          <%= cl_image_tag plane.photo.key %>
        <% else %>
          <img src="https://aircharterservice-globalcontent-live.cphostaccess.com/images/home_tcm36-2071.jpg" />
        <% end %>
        <div class="card-product-infos">
          <ul class="list-unstyled">
            <li><i class="fas fa-rocket"></i> <%= link_to booking.plane.name.to_s, plane_path(booking.plane), class: 'card-link' %><em> for </em><strong><%= booking.airline.name%></strong></li>
            <li><i class="fas fa-plane-departure"></i> <strong>Airport:</strong> <%= booking.plane.location %> </li>
            <li><i class="far fa-calendar-alt"></i> <strong>from:</strong> <%= booking.start_date.strftime("%d/%m/%Y")%> <strong>to:</strong> <%=booking.end_date.strftime("%d/%m/%Y")%></li>
            <% if booking.status == "pending" %>
              <li class="pt-2">
                <%= link_to "Accept", accepted_booking_path(booking),
                method: :patch, data: { confirm: "Sure to accept ? "},
                :class => "btn btn-primary" %>
                <%= link_to "Refuse", refused_booking_path(booking),
                method: :patch, data: { confirm: "Sure to refuse ? "},
                :class => "btn btn-danger" %>
              </li>
            <% else %>
              <li><i class="far fa-compass pt-2"></i> <strong>Status:</strong> <%= booking.status %></li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
</div>



<div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
  <div class="container d-flex mt-4" style ="justify-content: space-around;">
    <div class="container-left" style="width: 500px;">
      <h2 style="text-align: center;">Present</h2>
      <% @current_bookings_present.each do |booking| %>
        <div class="card-product mt-3">
          <% if booking.plane.photo.attached? %>
            <%= cl_image_tag plane.photo.key %>
          <% else %>
            <img src="https://aircharterservice-globalcontent-live.cphostaccess.com/images/home_tcm36-2071.jpg" />
          <% end %>
          <div class="card-product-infos">
            <ul class="list-unstyled">
              <li><i class="fas fa-rocket"></i> <%= link_to booking.plane.name.to_s, plane_path(booking.plane), class: 'card-link' %><em> for </em><strong><%= booking.airline.name%></strong></li>
              <li><i class="fas fa-plane-departure"></i> <strong>Airport:</strong> <%= booking.plane.location %> </li>
              <li><i class="far fa-calendar-alt"></i> <strong>from:</strong> <%= booking.start_date.strftime("%d/%m/%Y")%> <strong>to:</strong> <%=booking.end_date.strftime("%d/%m/%Y")%></li>
              <li><i class="far fa-compass pt-2"></i> <strong>Status:</strong> <%= booking.status %></li>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
    <div class="container-droite" style="width: 500px;">
      <h2 style="text-align: center;">Coming</h2>
      <% @current_bookings_futur.each do |booking| %>
        <div class="card-product mt-3">
          <% if booking.plane.photo.attached? %>
            <%= cl_image_tag plane.photo.key %>
          <% else %>
            <img src="https://aircharterservice-globalcontent-live.cphostaccess.com/images/home_tcm36-2071.jpg" />
          <% end %>
          <div class="card-product-infos">
            <ul class="list-unstyled">
              <li><i class="fas fa-rocket"></i> <%= link_to booking.plane.name.to_s, plane_path(booking.plane), class: 'card-link' %><em> for </em><strong><%= booking.airline.name%></strong></li>
              <li><i class="fas fa-plane-departure"></i> <strong>Airport:</strong> <%= booking.plane.location %> </li>
              <li><i class="far fa-calendar-alt"></i> <strong>from:</strong> <%= booking.start_date.strftime("%d/%m/%Y")%> <strong>to:</strong> <%=booking.end_date.strftime("%d/%m/%Y")%></li>
              <li><i class="far fa-compass pt-2"></i> <strong>Status:</strong> <%= booking.status %></li>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="tab-pane fade" id="nav-history" role="tabpanel" aria-labelledby="nav-history-tab">
  <div class="container mt-4">
      <% @old_bookings.each do |booking| %>
        <div class="card-product mt-3">
          <% if booking.plane.photo.attached? %>
            <%= cl_image_tag plane.photo.key %>
          <% else %>
            <img src="https://aircharterservice-globalcontent-live.cphostaccess.com/images/home_tcm36-2071.jpg" />
          <% end %>
          <div class="card-product-infos">
            <ul class="list-unstyled">
              <li><i class="fas fa-rocket"></i> <%= link_to booking.plane.name.to_s, plane_path(booking.plane), class: 'card-link' %><em> for </em><strong><%= booking.airline.name%></strong></li>
              <li><i class="fas fa-plane-departure"></i> <strong>Airport:</strong> <%= booking.plane.location %> </li>
              <li><i class="far fa-calendar-alt"></i> <strong>from:</strong> <%= booking.start_date.strftime("%d/%m/%Y")%> <strong>to:</strong> <%=booking.end_date.strftime("%d/%m/%Y")%></li>
              <% if booking.status == "pending" %>
                <li class="pt-2">
                  <%= link_to "Accept", accepted_booking_path(booking),
                  method: :patch, data: { confirm: "Sure to accept ? "},
                  :class => "btn btn-primary" %>
                  <%= link_to "Refuse", refused_booking_path(booking),
                  method: :patch, data: { confirm: "Sure to refuse ? "},
                  :class => "btn btn-danger" %>
                </li>
              <% else %>
                <li><i class="far fa-compass pt-2"></i> <strong>Status:</strong> <%= booking.status %></li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container text-center pt-5 w-500">
  <div class="form-style">
    <h2><%= @plane.name %></h2>
    <br>
    <%= simple_form_for [@plane, @booking] do |f| %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.submit "Book" %>
     <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAirbnf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%# ces deux lignes meta sont liées à Bootstrap %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%# <p class="notice"><%= notice</p> %>
    <%# <p class="alert"><%= alert</p> %>
    <div class="content-wrapper">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1517479149777-5f3b1511d5ad?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80);">
  <div class="container">
    <h1> AirBnF <strong> - Share </strong> my <strong> plane </strong> </h1>
    <p>We're helping your plane to feel the sky</p>
    <div class="form-inline mt-5 justify-content-center">
      <%= form_tag planes_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          style: "width: 250px",
          placeholder: "Plane or location or airline ?"
        %>
        <%= submit_tag "Search", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

  <div class="container text-center mt-5">
    <h2>How it works</h2>
    <div class="my-5">
      <div class="card-home my-4 d-flex align-items-center justify-content-around">
        <div class="p-2">
          <h3>You need a plane?</h3>
          <p> Discover all the planes offered by our community</p>
          <%= link_to "Discover", planes_path, class: "btn btn-outline-secondary" %>
        </div>
          <img src=https://images.unsplash.com/photo-1512221747435-73c38dd7afa1?ixlib=rb-1.2.1&auto=format&fit=crop&w=1625&q=80 alt="">
      </div>
      <div class="d-flex justify-content-end">
        <div class="card-home my-4 d-flex align-items-center justify-content-around">
          <img src=https://images.unsplash.com/photo-1496176744020-6fa84b9bbf15?ixlib=rb-1.2.1&auto=format&fit=crop&w=1381&q=80https://images.unsplash.com/photo-1496176744020-6fa84b9bbf15?ixlib=rb-1.2.1&auto=format&fit=crop&w=1381&q=80 alt="">
          <div>
            <h3>You have a plane?</h3>
            <p>Park it to your virtual warehouse and share it with our community</p>
            <%= link_to "Park my plane", my_planes_path, class: "btn btn-outline-secondary" %>

          </div>
        </div>
      </div>
    </div>
  </div>

app/views/planes/_info_window.html.erb
<div style="">
  <h5><%= plane.name %></h5>
  <p><%= plane.location %></p>
</div>

app/views/planes/create.html.erb
<% if policy(Plane).create? %>
  <%= link_to "New plane", my_planes_path %>
<% end %>

app/views/planes/edit.html.erb
<div class="container">
  <%= simple_form_for @plane do |f| %>
    <%= f.input :name %>
    <%= f.input :location %>
    <%= f.input :capacity %>
    <%= f.input :price_per_day %>
    <%= f.submit %>
  <% end %>
</div>

app/views/planes/index.html.erb
<div class="container d-flex my-5">
  <ul class="list-inline tabs-underlined">
  </ul>
  <div class="cards pr-3">
    <% @planes.each do |plane| %>
      <%= link_to plane_path(plane) do %>
        <div class="card-product" data-plane_id="<%= plane.id %>">
          <div style="height: 100%">
            <% if plane.photo.attached? %>
              <%= cl_image_tag plane.photo.key %>
            <% else %>
              <img src="https://aircharterservice-globalcontent-live.cphostaccess.com/images/home_tcm36-2071.jpg" />
            <% end %>
          </div>
          <div class="card-product-infos">
            <ul class="list-unstyled">
              <li>
                <div class="font-weight-bold"><%= plane.name %></div>
              </li>
              <li><i class="fas fa-user-friends"></i>  </i><%= plane.capacity %></li>
              <li><i class="fas fa-map-marked-alt"></i>  <%= plane.location %></li>
              <li><i class="fas fa-tags"></i>  <%= plane.price_per_day %> €</li>
            </ul>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div 
    id="map"
    style="width: 500px; height: 600px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/planes/my_planes.html.erb
<div class="container btn-add-plane ">
  <%= link_to "Add a new plane", new_plane_path %>
</div> 

<div class="container d-flex my-4">
  <div class="cards pr-3">
    <% @planes.each do |plane| %>
      <%= link_to plane_path(plane) do %>
        <div class="card-product" data-plane_id="<%= plane.id %>">
          <div style="height: 100%">
            <% if plane.photo.attached? %>
              <%= cl_image_tag plane.photo.key %>
            <% else %>
              <img src="https://aircharterservice-globalcontent-live.cphostaccess.com/images/home_tcm36-2071.jpg" />
            <% end %>
          </div>
          <div class="card-product-infos">
            <ul class="list-unstyled">
              <li>
                <div class="font-weight-bold"><%= plane.name %></div>
              </li>
              <li><i class="fas fa-user-friends"></i>  </i><%= plane.capacity %></li>
              <li><i class="fas fa-map-marked-alt"></i>  <%= plane.location %></li>
              <li><i class="fas fa-tags"></i>  <%= plane.price_per_day %> €</li>
            </ul>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/planes/myplanes.html.erb
<div class="container">
  <ul class="list-inline tabs-underlined">
    <li>
      <%= link_to "Add a new plane", new_plane_path, class: "tab-underlined active" %>
    </li>
  </ul>
  <div class="cards">
    <% @planes.each do |plane| %>
      <div class="card-product">
        <% if plane.photo.attached? %>
          <%= cl_image_tag plane.photo.key %>
        <% else %>
          <img src="https://aircharterservice-globalcontent-live.cphostaccess.com/images/home_tcm36-2071.jpg" />
        <% end %>
        <div class="card-product-infos">
            <ul class="list-unstyled">
              <li>
                <div><%= link_to plane.name.to_s, plane_path(plane) %></div>
              </li>
            </ul>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/planes/new.html.erb
<div class="container text-center">
  <div class="form-style" style="width: 100%">
    <%= simple_form_for @plane do |f| %>
      <div class="d-flex justify-content-between">
        <div style="width: 50%">
          <%= f.input :name %>
          <%= f.input :location %>
          <%= f.input :capacity %>
          <%= f.input :price_per_day %>
        </div>
        <div style="width: 40%">
          <%= f.submit %>
          <%# <%= f.input :photo, as: :file %>
          <%# <%= f.input :photo, input_html: { class: 'd-none'}, label_html: { class: 'upload-photo'}, label: '📷 Upload a photo' %>
          <%= image_tag "", width: 300, class: "hidden", id: "photo-preview" %>
          <%= f.input :photo, input_html: { class: 'd-none', id: 'photo-input'}, label_html: { class: 'upload-photo'}, label: '📷 Upload a photo' %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="container">
  <%= link_to "<< Back", my_planes_path %>
</div>

app/views/planes/show.html.erb
<div class="container d-flex" style="min-height: calc(100vh - 70px - 120px); align-items: center; padding-bottom:150px;">
  <div class="row" style="height: 300px;">
    <div class="card-trip mt-5 mr-4">
      <% if @plane.photo.attached? %>
        <%= cl_image_tag @plane.photo.key, height: 300, width: 400, crop: :fill %>
      <% else %>
        <img src="https://aircharterservice-globalcontent-live.cphostaccess.com/images/home_tcm36-2071.jpg" />
      <% end %>
      <div class="card-trip-infos">
        <div style="width: 100%">
          <h1> <%= @plane.name %></h1>
          <ul class="list-unstyled">
            <div class="d-flex justify-content-between">
              <li><i class="fas fa-user-friends"></i>  <%= @plane.capacity %></li>
              <li><i class="fas fa-map-marked-alt"></i>  <%= @plane.location %></li>
              <li><i class="fas fa-tags"></i>  <%= @plane.price_per_day %> €</li>
            </div>
          </ul>
        <div>
          <% if policy(@plane).edit? %>
            <%= link_to "Update", edit_plane_path(@plane) %>
          <% end %>
          <% if policy(@plane).destroy? %>
            <%= link_to "Delete", plane_path(@plane), method: :delete, data: { confirm: "Are you sure?" } %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <% if policy(@booking).new? %>
      <div class="form-style pt-3">
        <%= simple_form_for [@plane, @booking] do |f| %>
        <%= f.input :start_date %>
        <%= f.input :end_date %>
        <%= f.submit "Book" %>
        <% end %>
      </div>
    <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    © 2020 Airbnf, Inc. All rights reserved
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://dcassetcdn.com/design_img/2072594/153100/153100_11027771_2072594_a3fd3d07_image.jpg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if airline_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "All planes", planes_path, class: "nav-link" %>
        </li>
        <li class="nav-link ml-5"><%= current_airline.email %></li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/tylapo", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My bookings", bookings_path, class: "dropdown-item" %>
            <%= link_to "My planes", my_planes_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_airline_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_airline_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>